/**
 * Reusable AI Enhancement Utilities for Tutor & Chat
 * Shared functions for error correction, context memory, confidence scoring, etc.
 */

export interface ResponseEnhancement {
  original: string;
  withCorrection?: string;
  confidence?: number;
  source?: string;
  alternatives?: string[];
  culturalContext?: string;
  pronunciation?: string;
}

export interface ConversationMemory {
  userId: string;
  sessionId: string;
  learningTopics: string[];
  mistakePatterns: string[];
  successPatterns: string[];
  lastUpdated: Date;
}

/**
 * Error Correction Feedback
 * Analyzes response and provides structured correction
 */
export function generateErrorFeedback(
  userInput: string,
  correctForm: string,
  errorType: "grammar" | "vocabulary" | "pronunciation" | "dialect"
): string {
  const feedback: Record<string, string> = {
    grammar: `Grammar correction: "${userInput}" → "${correctForm}"\nRule: Check SOV word order (Subject-Object-Verb)`,
    vocabulary: `Vocabulary correction: "${userInput}" → "${correctForm}"\nNote: Use Tedim ZVS standard (pasian, gam, tapa, not pathian, ram, fapa)`,
    pronunciation: `Pronunciation: "${userInput}" should sound like "${correctForm}"\nTip: Remember "o" = /oʊ/ sound`,
    dialect: `Dialect correction: "${userInput}" → "${correctForm}"\nContext: This is the Tedim ZVS standard form`,
  };
  return feedback[errorType] || feedback.grammar;
}

/**
 * Confidence Scoring
 * Returns confidence level (0-1) based on response certainty
 */
export function scoreConfidence(
  response: string,
  hasSourceAttribution: boolean,
  isFromCorpus: boolean
): number {
  let score = 0.5; // base
  if (hasSourceAttribution) score += 0.2;
  if (isFromCorpus) score += 0.3;
  if (response.length > 50) score += 0.1; // longer = more detailed
  return Math.min(score, 1);
}

/**
 * Source Attribution
 * Adds source reference to response
 */
export function addSourceAttribution(
  response: string,
  source: "bible" | "dictionary" | "wiki" | "corpus" | "ai"
): string {
  const sources: Record<string, string> = {
    bible: "[Source: Bible Corpus - TDB77/TBR17/Tedim2010]",
    dictionary: "[Source: Zolai Dictionary - 24,891 entries]",
    wiki: "[Source: Zolai Linguistics Wiki]",
    corpus: "[Source: Zolai Master Corpus]",
    ai: "[Generated by AI - verify with native speaker]",
  };
  return `${response}\n\n${sources[source]}`;
}

/**
 * Alternative Responses
 * Generates multiple valid ways to express the same idea
 */
export function generateAlternatives(
  primaryResponse: string,
  context: "formal" | "casual" | "poetic"
): string[] {
  // Placeholder for LLM-generated alternatives
  // In production, call LLM with prompt:
  // "Generate 2 alternative ways to say: [primaryResponse] in [context] Zolai"
  return [
    primaryResponse,
    `[Alternative 1 - ${context}]`,
    `[Alternative 2 - ${context}]`,
  ];
}

/**
 * Cultural Context Explanation
 * Adds cultural significance to responses
 */
export function addCulturalContext(
  word: string,
  explanation: string
): string {
  return `${word}\n📖 Cultural Context: ${explanation}`;
}

/**
 * Pronunciation Guide
 * Provides IPA and practical pronunciation tips
 */
export function generatePronunciationGuide(
  word: string,
  ipa: string,
  tips: string
): string {
  return `${word}\n🔊 IPA: ${ipa}\n💡 Tip: ${tips}`;
}

/**
 * Progress Tracking
 * Tracks learning patterns and adjusts difficulty
 */
export function updateLearningProgress(
  memory: ConversationMemory,
  topic: string,
  success: boolean
): ConversationMemory {
  const updated = { ...memory, lastUpdated: new Date() };
  
  if (success) {
    updated.successPatterns = [...new Set([...updated.successPatterns, topic])];
  } else {
    updated.mistakePatterns = [...new Set([...updated.mistakePatterns, topic])];
  }
  
  if (!updated.learningTopics.includes(topic)) {
    updated.learningTopics.push(topic);
  }
  
  return updated;
}

/**
 * Difficulty Adjustment
 * Recommends next level based on progress
 */
export function recommendNextLevel(
  currentLevel: "A1" | "A2" | "B1" | "B2" | "C1" | "C2",
  successRate: number
): "A1" | "A2" | "B1" | "B2" | "C1" | "C2" {
  const levels = ["A1", "A2", "B1", "B2", "C1", "C2"];
  const currentIndex = levels.indexOf(currentLevel);
  
  if (successRate >= 0.8 && currentIndex < levels.length - 1) {
    return levels[currentIndex + 1] as "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
  }
  if (successRate < 0.5 && currentIndex > 0) {
    return levels[currentIndex - 1] as "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
  }
  return currentLevel;
}

/**
 * Code-Switching Detection
 * Identifies when user mixes Zolai and English
 */
export function detectCodeSwitching(text: string): {
  hasZolai: boolean;
  hasEnglish: boolean;
  ratio: number;
} {
  const zolaiPatterns = /\b(pasian|gam|tapa|topa|kumpipa|tua|hi|hiam|in|a|uh)\b/gi;
  const englishWords = text.split(/\s+/).filter(w => /^[a-z]+$/i.test(w));
  
  const zolaiMatches = (text.match(zolaiPatterns) || []).length;
  const totalWords = text.split(/\s+/).length;
  
  return {
    hasZolai: zolaiMatches > 0,
    hasEnglish: englishWords.length > 0,
    ratio: zolaiMatches / totalWords,
  };
}

/**
 * Idiom/Proverb Explanation
 * Detects and explains Zolai idioms
 */
export function explainIdiom(idiom: string): string {
  const idioms: Record<string, string> = {
    "lungdam mahmah": "Very happy/grateful (literally: heart-good very)",
    "lungkhual": "Thoughtful/considerate (literally: heart-think)",
    "lungkham": "Sad/disappointed (literally: heart-break)",
    "thakhauhin hang": "Be strong/courageous (literally: strength-hold emphatic)",
  };
  
  return idioms[idiom.toLowerCase()] || `Idiom: ${idiom} (explanation needed)`;
}

/**
 * Dictionary Lookup Integration
 * Provides real-time word definitions
 */
export async function lookupWord(
  word: string,
  dictionaryUrl: string = "/api/dictionary/search"
): Promise<{ word: string; definition: string; examples: string[] } | null> {
  try {
    const res = await fetch(`${dictionaryUrl}?q=${encodeURIComponent(word)}`);
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  }
}

/**
 * Feedback Loop Integration
 * Learns from user corrections
 */
export function processFeedback(
  originalResponse: string,
  userCorrection: string,
  feedbackType: "helpful" | "incorrect"
): { learned: boolean; pattern: string } {
  if (feedbackType === "incorrect") {
    return {
      learned: true,
      pattern: `Avoid: "${originalResponse}" → Use: "${userCorrection}"`,
    };
  }
  return {
    learned: true,
    pattern: `Reinforce: "${originalResponse}" is correct`,
  };
}

/**
 * Response Quality Metrics
 * Evaluates response quality
 */
export function evaluateResponseQuality(response: string): {
  score: number;
  issues: string[];
} {
  const issues: string[] = [];
  let score = 100;
  
  if (response.length < 10) {
    issues.push("Response too short");
    score -= 20;
  }
  if (!response.includes("hi") && !response.includes("hiam")) {
    issues.push("Missing Zolai sentence ending (hi/hiam)");
    score -= 15;
  }
  if (response.includes("pathian") || response.includes("ram")) {
    issues.push("Using forbidden dialect forms");
    score -= 30;
  }
  if (!response.includes("English") && response.length > 50) {
    issues.push("No English explanation provided");
    score -= 10;
  }
  
  return { score: Math.max(score, 0), issues };
}
